# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  print-hello:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run:
          name: "Say hello"
          command: echo hello
  
  print-world:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run:
          name: "Say world"
          command: echo world

  print-env-var:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run:
          name: "Say my name-valued environment variable"
          command: echo $_My_Name

workflows:
  say-hello-world:
    jobs:
      - print-hello
      - print-world:
          requires:
            - print-hello
      - print-env-var:
          requires:
            - print-world
